Api install
avorty/spito pull request #107
Opened 2024-02-10 19:03 UTC by sewe2000

Add ability to install and remove system packages in rules + fix some bugs.

2024-02-11 13:42 UTC, BaderBC commented on internal/checker/api_binding.go
>  	apiNamespace.AddField("info", getInfoNamespace(importLoopData, L))
Info namespace and Package namespace both takes the same arfuments, but in different order
Please make it consistent (I propose changing Info namespace arguments order)

2024-02-12 09:15 UTC, cooligus requested changes
You can also add Resolves #82

2024-02-12 09:15 UTC, cooligus commented on cmd/generate.go
> +		rulePath = strings.TrimSuffix(rulePath, ".lua")
I think you can use `TrimSuffix` without if above

2024-02-12 09:15 UTC, cooligus commented on pkg/package_conflict/package_conflict_tracker.go
> +		return errors.New(fmt.Sprintf("[PACKAGE_CONFLICT] the package %s is required to be uninstalled by a dependency", packageName))
```suggestion
		return fmt.Errorf("[PACKAGE_CONFLICT] the package %s is required to be uninstalled by a dependency", packageName)
```

2024-02-16 20:03 UTC, BaderBC requested changes
As I previously said - we need to install packages immediately, because sometimes e.g. installing package may override your changes or config which you wanna modify should be created while installing package

2024-02-17 11:04 UTC, cooligus approved these changes

2024-02-17 13:12 UTC, sewe2000 commented
> As I previously said - we need to install packages immediately, because sometimes e.g. installing package may override your changes or config which you wanna modify should be created while installing package

What do you mean by that?

2024-02-17 17:26 UTC, cooligus requested changes
![1](https://github.com/avorty/spito/assets/67282004/0357c0d1-3c02-4e92-884c-eaaf620d2375)
![2](https://github.com/avorty/spito/assets/67282004/a121e006-3df4-4cd1-b957-30b6d112c5f4)

2024-02-17 18:52 UTC, BaderBC requested changes
- Implement progress bar in `api.info` then use it automatically when installing package
- Add support for aur packages
- Add tests

2024-02-23 11:38 UTC, cooligus approved these changes
I don't like idea of installing package before applying rule, but...

Edit:
I also realized that installing packages from aur also requires root (issue welcome).

2024-02-24 14:12 UTC, BaderBC approved these changes

2024-02-24 15:14 UTC, merged