gh actions caching
avorty/spito pull request #108
Opened 2024-02-10 22:47 UTC by BaderBC

2024-02-10 23:17 UTC, BaderBC commented
If you wonder why this doesn't pass look at #109

2024-02-11 17:28 UTC, maxidragon reviewed
I think this won't work. Maybe we can use [docker-cache](https://github.com/marketplace/actions/docker-cache)?

2024-02-11 17:30 UTC, BaderBC commented
> I think this won't work. Maybe we can use [docker-cache](https://github.com/marketplace/actions/docker-cache)?

I will try this, but fristly @cooligus should resolve his #109

2024-02-12 08:31 UTC, cooligus requested changes

2024-02-12 08:31 UTC, cooligus commented on .github/workflows/tests.yml
> +
Why do you pull these images (9 times)?

2024-02-15 17:23 UTC, BaderBC commented
It seems that paradoxically caching docker images and/or layers even slows down tests CI
That's why I close this pr

2024-02-15 17:23 UTC, closed without merging