mapping errors to strings
avorty/spito pull request #129
Opened 2024-02-28 16:58 UTC by BaderBC

2024-02-28 17:02 UTC, maxidragon approved these changes

2024-02-28 17:02 UTC, maxidragon commented on internal/checker/api_binding.go
> +		// It thorws panic, because if I would avoid it, fnType.NumIn() would panic which would be harder to debug
```suggestion
		// It throws panic, because if I would avoid it, fnType.NumIn() would panic which would be harder to debug
```

2024-02-28 17:05 UTC, cooligus requested changes

2024-02-28 17:05 UTC, cooligus commented on internal/checker/api_binding.go
> +func isTypeError(t reflect.Type) bool {
```suggestion
func getErrorType() reflect.Type {
return reflect.TypeOf((*error)(nil)).Elem()
}
```

2024-02-28 17:09 UTC, cooligus requested changes

2024-02-28 17:09 UTC, cooligus commented on internal/checker/api_binding.go
> +	reflectErrType := reflect.TypeOf((*error)(nil)).Elem()
```suggestion
```

2024-02-28 17:09 UTC, cooligus commented on internal/checker/api_binding.go
> +			if !result.Type().Implements(reflectErrType) {
```suggestion
			if !isTypeError(result) {
```

2024-02-29 08:26 UTC, cooligus approved these changes

2024-02-29 08:28 UTC, merged