Add the ability to create new ruleset and new rule
avorty/spito pull request #47
Opened 2023-12-17 12:31 UTC by sewe2000

Resolves #35

2023-12-18 15:57 UTC, maxidragon commented on src/checker/ruleset_location.go
> +	println(r.GetRuleSetPath())
```suggestion
```

2023-12-18 19:02 UTC, cooligus reviewed
I suggest to change names of these commands:
`nr` or `new rule` - to create rule
`ns` or `new set` - to create set

2023-12-19 14:01 UTC, sewe2000 commented
> I suggest changing names of these commands: `nr` or `new rule` - to create rule `ns` or `new set` - to create set

@BaderBC What do you think about it?

2023-12-19 14:29 UTC, BaderBC commented
> > I suggest changing names of these commands: `nr` or `new rule` - to create rule `ns` or `new set` - to create set
> 
> @BaderBC What do you think about it?

Even though It sounds good I'm not sure whether it is necessary, especially that `new rule` isn't the command which would be often used.

2023-12-19 14:37 UTC, sewe2000 commented
> > > I suggest changing names of these commands: `nr` or `new rule` - to create rule `ns` or `new set` - to create set
> > 
> > 
> > @BaderBC What do you think about it?
> 
> Even though It sounds good I'm not sure whether it is necessary, especially that `new rule` isn't the command which would be often used.

The thing is I've implemented the process of creating a new rule, but the command is ```generate {rule_name}````. @cooligus suggested to change it to ```new rule {rule_name}```

2023-12-19 16:06 UTC, BaderBC commented
> > > > I suggest changing names of these commands: `nr` or `new rule` - to create rule `ns` or `new set` - to create set
> > > 
> > > 
> > > @BaderBC What do you think about it?
> > 
> > Even though It sounds good I'm not sure whether it is necessary, especially that `new rule` isn't the command which would be often used.
> 
> The thing is I've implemented the process of creating a new rule, but the command is ```generate {rule_name}````. @cooligus suggested to change it to ```new rule {rule_name}```

Okay,
Now I understand. Personally i prefer to do it the same way Nest.js cli did it - `generate`

2023-12-20 11:04 UTC, cooligus approved these changes

2023-12-20 11:56 UTC, BaderBC requested changes

2023-12-20 11:56 UTC, BaderBC commented on src/cmd/generate.go
> +	if !rulesetLocation.IsRuleSetDownloaded() {
I don't understand this line
When someone is downloading a new ruleset it does makes sens that it needs to be putted into specific directory.
But if someone just wants to create a new rule in ruleset it should look like a normal project, meaning that it should be allowed to create ruleset wherever you want to.

2023-12-20 11:56 UTC, BaderBC commented on src/cmd/generate.go
> +	ruleFile, error := os.Create("rules/" + ruleName + ".lua")
I think it should be possible to create new rule in subdirectory e.g. create rule in `rules/example/dir/rule.lua`

2023-12-20 11:56 UTC, BaderBC commented on src/cmd/new.go
> +		gitCommand := exec.Command("git", "config", "--global", "--list")
I think it is better idea to use library for git (especially that checker module already imports library for git)

2023-12-20 11:56 UTC, BaderBC commented on src/cmd/root.go
> +	generateShortCommand.Flags().Bool("gui-child-mode", false, "Tells app that it is executed by gui")
I don't think it is needed for your command, because I created this flag only in order to redirect all api.info.* to dbus

2023-12-21 19:52 UTC, BaderBC requested changes
I have only one question:  Have you ever tested it?
![image](https://github.com/avorty/spito/assets/80683535/96838876-ef64-452d-b286-3fbb05e3c2c0)

2023-12-22 19:31 UTC, BaderBC requested changes
`spito new test-ruleset` generated this `spito-rules.yml` file:
```
repo_url: https://github.com/Bartłomiej Strama/test-ruleset
git_prefix: github.com
identifier: Bartłomiej Strama/test-ruleset
rules:
    example-rule: ./rules/dir2/subdir/example-rule.lua
```

Because of repo_url value, which it automaticly created, I think after executing `spito new` we should ask few questions like: what is your repo url (simillary to what happens when you execute `npm init`)
Don't forget to add option `-y` which will choose default `spito-rules.yml` values

2023-12-23 19:11 UTC, BaderBC approved these changes

2023-12-23 20:51 UTC, merged