Change project layout
avorty/spito pull request #55
Opened 2023-12-23 22:06 UTC by cooligus

2023-12-24 14:45 UTC, BaderBC requested changes

2023-12-24 14:45 UTC, BaderBC commented on pkg/api/lua_tests/lua_api_test.go
> +			RulesHistory: shared2.RulesHistory{},
why it is `shared2` instead of `shared`

2023-12-24 14:53 UTC, maxidragon reviewed
I think all imports should be changed to `avorty/spito` instead of `nasz-elektryk/spito`. @BaderBC please correct me if I'm wrong

2023-12-27 19:56 UTC, BaderBC approved these changes

2023-12-27 19:58 UTC, maxidragon approved these changes

2023-12-27 19:59 UTC, merged